### ISSUE TITLE
docs website have ssl issue

### ISSUE THREAD

**Issue by Bnaya** [AssemblyScript/website#3]
At url:
https://docs.assemblyscript.org/

![Screen Shot 2020-06-07 at 12 25 09](https://user-images.githubusercontent.com/1304862/83965175-6760c500-a8ba-11ea-8089-a10ed0628370.png)
![Screen Shot 2020-06-07 at 12 29 04](https://user-images.githubusercontent.com/1304862/83965195-81020c80-a8ba-11ea-9774-0df47bbabb00.png)

**Comment by dcodeIO** [comment]
The docs have been moved to [the new website](https://assemblyscript.org/) and there seem to be some issues because we are using a TLD (assemblyscript.org without www) as a GitHub page there. While the main site works, my attempts to configure the old `docs.assemblyscript.org`, which now redirects to the new website, to work with https have failed so far.

From the GitHub docs I figured that there might be issues in such configurations and they don't support it properly. Not sure, but if so, that's kinda unfortunate. If someone knows how to configure this correctly, i.e. that GitHub makes a LetsEncrypt cert for both the TLD and any subdomain like www or docs, let me know.

**Comment by dcodeIO** [comment]
Certificate for `docs.` should be correct now. When I opened the settings page again, it showed a 'SSL certificate is being provisioned' message. In case you'd like to verify, make sure to restart your browser so it reloads the cert. Should be green then.

[Test link](https://docs.assemblyscript.org/404)

**Comment by dcodeIO** [comment]
What's still not working is `www.`, though. Not sure if that can be fixed :(

[Test link with www](https://www.assemblyscript.org/404)
[Test link without www](https://assemblyscript.org/404)

**Comment by dcodeIO** [comment]
For reference, [this redirect](https://github.com/AssemblyScript/website-www) does not work due to a page build warning 'The CNAME `www.assemblyscript.org` is already taken, yet GitHub does not provision a certificate for `www.` as well when using `CNAME assemblyscript.org` on the [page](https://github.com/AssemblyScript/website/blob/gh-pages/CNAME) already taking it indirectly by specifying the TLD.

**Comment by Bnaya** [comment]
First google result is to `docs.`
Adding a permanent redirect may help  
![Screen Shot 2020-06-07 at 20 10 08](https://user-images.githubusercontent.com/1304862/83975145-e83fb100-a8fa-11ea-91d6-544107836d9f.png)

**Comment by dcodeIO** [comment]
There is no such thing as "permanent redirect" when using GitHub pages exclusively, unfortunately, unless I configure these alias domains externally, for example with Cloudflare. That's an option of course if everything else fails, and I know how to do it, but I first want to try to get it working with just GitHub because I think there must, and if it isn't then there should, be a way.

**Comment by dcodeIO** [comment]
Btw, the installed redirects specify a canonical URL, so the search results should update eventually.

**Comment by dcodeIO** [comment]
I *think* I've sorted it out now. When using `www.assemblyscript.org` on the website repo, we get a LetsEncrypt SSL cert for both `assemblyscript.org` and `www.assemblyscript.org`, with the former being a redirect to the latter. Now that means we can't use just `assemblyscript.org`, since if someone copies a link they'll have that `www.`, but we can still use it in our links. Overall setup now is:

* www.assemblyscript.org (website with cert)
* assemblyscript.org (github-provided redirect to www.assemblyscript.org with cert)
* docs.assemblyscript.org (legacy redirects with cert)

Should also be possible to enforce HTTPS now.

All the links to verify (remember to close and reopen your browser once):

* http://assemblyscript.org/404
* https://assemblyscript.org/404
* http://www.assemblyscript.org/404
* https://www.assemblyscript.org/404
* http://docs.assemblyscript.org/404
* https://docs.assemblyscript.org/404

**Comment by dcodeIO** [comment]
Closing as this seems to be sorted now. Feel free to reopen if necessary :)
